#!/bin/bash

#Given a sentence, identify and display its fourth word. Assume that the 
#space (' ') is the only delimiter between words.


#code
cut -d ' ' -f 4
#To Follow -> https://github.com/sariamubeen
