#!/bin/bash

#Given a tab delimited file with several columns (tsv format) print the 
#fields from second fields to last field.


#code

cut -d $'\t' -f2-

#To Follow -> https://github.com/sariamubeen
