#!/bin/bash

#Given a sentence, identify and display its first three words. Assume that 
#the space (' ') is the only delimiter between words.


#code
cut -d ' ' -f 1-3
#To Follow -> https://github.com/sariamubeen
