#!/bin/bash

challenge_names=(
"Matching Specific String"
"Matching Anything But a Newline"
"Matching Digits & Non-Digit Characters"
"Matching Whitespace & Non-Whitespace Character"
"Matching Word & Non-Word Character"
"Matching Start & End"
"Matching Specific Characters"
"Excluding Specific Characters"
"Matching Character Ranges"
"Matching {x} Repetitions"
"Matching {x, y} Repetitions"
"Matching Zero Or More Repetitions"
"Matching One Or More Repetitions"
"Matching Ending Items"
"Matching Word Boundaries"
"Capturing & Non-Capturing Groups"
"Alternative Matching"
"Matching Same Text Again & Again"
"Backreferences To Failed Groups"
"Branch Reset Groups"
"Forward References"
"Positive Lookahead"
"Negative Lookahead"
"Positive Lookbehind"
"Negative Lookbehind"
"Detect HTML links"
"Detect HTML Tags"
"Find A Sub-Word"
"Alien Username"
"IP Address Validation"
"Find a Word"
"Detect the Email Addresses"
"Detect the Domain Name"
"Building a Smart IDE: Identifying comments"
"Detecting Valid Latitude and Longitude Pairs"
"HackerRank Tweets"
"Build a Stack Exchange Scraper"
"Utopian Identification Number"
"Valid PAN format"
"Find HackerRank"
"Saying Hi"
"HackerRank Language"
"Split the Phone Numbers"
"Detect HTML Attributes"
"The British and American Style of Spelling"
"UK and US: Part 2"
)

for challenge_name in "${challenge_names[@]}"; do
    touch "$challenge_name"
done

