#!/bin/bash

#Read in one character from STDIN.
#If the character is 'Y' or 'y' display "YES".
#If the character is 'N' or 'n' display "NO".
#No other character will be provided as input.

#code

# Prompt the user for input
echo "Please enter a single character (Y/N):"
read -n 1 input

# Check the input character
if [ "$input" == "Y" ] || [ "$input" == "y" ]; then
    echo "YES"
elif [ "$input" == "N" ] || [ "$input" == "n" ]; then
    echo "NO"
fi




#To Follow -> https://github.com/sariamubeen
