#!/bin/bash

#Given three integers (X, Y, and Z) representing the three sides of a triangle, identify whether the #triangle is scalene, isosceles, or equilateral.

#If all three sides are equal, output EQUILATERAL.
#Otherwise, if any two sides are equal, output ISOSCELES.
#Otherwise, output SCALENE.

#code

# Input values
read X
read Y 
read Z

# Check the type of triangle
if [ "$X" -eq "$Y" ] && [ "$Y" -eq "$Z" ]; then
    echo "EQUILATERAL"
elif [ "$X" -eq "$Y" ] || [ "$Y" -eq "$Z" ] || [ "$Z" -eq "$X" ]; then
    echo "ISOSCELES"
else
    echo "SCALENE"
fi


#To Follow -> https://github.com/sariamubeen
